# Generated by Django 2.1 on 2020-04-28 14:00

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solar', models.FileField(upload_to='')),
                ('wind', models.FileField(upload_to='')),
                ('house', models.FileField(upload_to='')),
                ('row', models.IntegerField()),
                ('coal', django_mysql.models.ListTextField(models.IntegerField(), size=100)),
                ('store', django_mysql.models.ListTextField(models.IntegerField(), size=100)),
                ('window', models.CharField(max_length=3)),
                ('non_renewable', models.CharField(max_length=3)),
                ('ddate', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
