# Generated by Django 2.1 on 2020-04-28 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('major', '0004_auto_20200428_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prediction',
            name='resi',
            field=models.IntegerField(blank=True, default=None, max_length=2, null=True),
        ),
    ]
